### ISSUE TITLE
Fastboot device not found, how to fix?

### ISSUE THREAD

**Issue by wufixx** [rendiix/termux-adb-fastboot#1]
Fastboot device not found, how to fix?

**Comment by rendiix** [comment]
> Fastboot device not found, how to fix?

Can you send the output of termux-info, and fastboot version.

**Comment by wufixx** [comment]
$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# sources.list.d/rendiix.list
deb https://rendiix.github.io android-tools termux
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf-g444c25f #1 SMP PREEMPT Thu May 21 23:00:48 CST 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
MI 9
fastboot --version
fastboot version 9.0.1-termux-android-arm64-v8a-gkdev
Installed as /data/data/com.termux/files/usr/bin/fastboot

**Comment by rendiix** [comment]
@wufixx Try running fastboot with root. Libusb cannot access / dev/bus/usb/ * without root

**Comment by wufixx** [comment]
Belum di-root hpnya bg
