### ISSUE TITLE
adb cannot locate symbol "pthread_cond_clockwait"

### ISSUE THREAD

**Issue by wyhxf** [rendiix/termux-adb-fastboot#13]
~ $ adb
CANNOT LINK EXECUTABLE "adb": cannot locate symbol "pthread_cond_clockwait" referenced by "/data/data/com.termux/files/usr/bin/adb"...

TERMUX_VERSION=0.118.0
Updatable packages:
All packages up to date
termux-tools version:
1.29.1
Android version:
10

**Comment by rendiix** [comment]
Will fix it soon, thank you

**Comment by rendiix** [comment]
should be fixed in https://github.com/rendiix/termux-adb-fastboot/commit/0d751a226f5a651b77ade8c74f7f6fb7eb13aee4
