### ISSUE TITLE
Cannot connect to device

### ISSUE THREAD

**Issue by MelleNi** [rendiix/termux-adb-fastboot#7]
After installing, when I try to start server and find connected devices I get the following:
![Screenshot_20211217-163348_Termux](https://user-images.githubusercontent.com/2730018/146578169-40c080f4-5b21-460f-9622-091820964dbc.jpg)

**Comment by rendiix** [comment]
@MelleNi Use wireless debugging to connect from the device itself

**Comment by MelleNi** [comment]
@rendiix I tried that, but the only way I could do it in the end was by doing a fresh install (after which it wouldn't display any devices at all) and then the following:

 Connecting to a computer, and then running:
`adb tcpip 5555`
`adb kill-server`
on the computer, disconnecting the cable and running on the phone:
`adb connect localhost:5555`

**Comment by rendiix** [comment]
The device must be connected to the local network via wifi. Then do adb pairing. 


![Screenshot_20211218-011707954](https://user-images.githubusercontent.com/16639978/146589938-43bb42ee-9c1c-4be3-bfd7-028b4837619c.jpg)

**Comment by MelleNi** [comment]
It says pairing is unsuccessful, and that I have to connect to the same network, even though it is of course connected to the same network.

**Comment by nathaneltitane** [comment]
doesn't work, followed instructions and pairing guide to a Tee...

![Screenshot_20220106-134339_Termux](https://user-images.githubusercontent.com/5674757/148434391-14f848f3-8b86-4d96-8d8e-2360e688c1d4.png)

**Comment by MelleNi** [comment]
> doesn't work, followed instructions and pairing guide to a Tee...

Did you try do the steps I did? Doing that it worked for me, after that you don't need a computer anymore to set it up

**Comment by nathaneltitane** [comment]
> > doesn't work, followed instructions and pairing guide to a Tee...
> 
> Did you try do the steps I did? Doing that it worked for me, after that you don't need a computer anymore to set it up

yes actually.. unless i gorgot something?

can you write a step by step to be sure?, i'll try once more?

**Comment by MelleNi** [comment]
> 

1. Connect your device to a computer
2. On the computer you make sure the device shows up with `adb devices`
3. On the computer you do `adb tcpip 5555` and then `adb kill-server`
4. Disconnect the phone from the computer
5. On the phone you do `adb connect localhost:5555`
6. It should now connect

I think that's all the steps, but it's from memory, so I might be wrong.

It's similar to this wi-fi guide: https://www.guru99.com/adb-connect.html

**Comment by heham** [comment]
> > 
> 
>     1. Connect your device to a computer
> 
>     2. On the computer you make sure the device shows up with `adb devices`
> 
>     3. On the computer you do `adb tcpip 5555` and then `adb kill-server`
> 
>     4. Disconnect the phone from the computer
> 
>     5. On the phone you do `adb connect localhost:5555`
> 
>     6. It should now connect
> 
> 
> I think that's all the steps, but it's from memory, so I might be wrong.
> 
> It's similar to this wi-fi guide: https://www.guru99.com/adb-connect.html

Thank you! It worked!
